### ISSUE TITLE
How to use in Kubuntu?

### ISSUE THREAD

**Issue by elcste** [Tarptaeya/PDFReader#1]
I'm very interested in this because I enjoy using PDF.js in Firefox, but I don't know how get it to work in Kubuntu 18.10 (with Falkon installed from the Ubuntu archive).

I followed the build instructions in the README, and I don't get any errors. I see it gets installed to `/usr/local/lib/x86_64-linux-gnu/plugins/falkon/qml/pdfreader`. Do I need to enable something somewhere? Should it show up in Falkon's extension settings?
 
FWIW, it looks like the bundled Falkon extensions are installed in '/usr/lib/x86_64-linux-gnu/qt5/plugins/falkon', but they are all `.so` files like `AutoScroll.so`.

Thanks!

**Comment by tarptaeya** [comment]
Thanks for your interest, You have to build and install falkon from source as falkon from the archive doesn't have support for QML plugins which was added after the release of 3.0.1.

Regards

**Comment by elcste** [comment]
Aha, I will give that try! Thanks!

**Comment by elcste** [comment]
I had a chance to try Falkon compiled from git, and this plugin works great! Do you accept donations somewhere so I can buy you a coffee/beer?

**Comment by tarptaeya** [comment]
Thanks for your interest. I don't accept donations but you can instead star this repo and follow me on GitHub :)
